---
- name: install | Create NSO working directory
  ansible.builtin.file:
    path: "{{ nso_root_dir }}"
    state: directory
    mode: '0755'

- name: install | Copy signed binary to remote host
  ansible.builtin.copy:
    src: "{{ nso_signed_binary }}"
    dest: "{{ bin_working_dir }}"
    mode: '0755'
  when: ansible_host != "localhost"

- name: install | Unpack signed binary
  ansible.builtin.command: "sh {{ nso_signed_binary }} --skip-verification"
  args:
    chdir: "{{ bin_working_dir }}"
    creates: "{{ nso_install_binary }}"

- name: install | Run local installation
  ansible.builtin.command: "sh {{ nso_install_binary }} --local-install {{ nso_install_dir }}"
  args:
    chdir: "{{ bin_working_dir }}"
    creates: "{{ nso_install_dir }}"

- name: install | Install external YANG files
  ansible.builtin.include_tasks: "yang-files.yml"
  when: nso_yang_files is defined and nso_yang_files
