---
# tasks file for ansible-nso-local-install
- name: main | Gather operating system variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - "always"

- name: main | Pre-flight
  ansible.builtin.include_tasks: "pre-flight.yml"
  tags:
    - "always"

- name: main | Install
  ansible.builtin.include_tasks: "install.yml"
  tags:
    - "always"

- name: main | Runtime
  ansible.builtin.include_tasks: "runtime.yml"
  tags:/build/building/multi-platform/
    - "always"

- name: main | NED packages
  ansible.builtin.include_tasks: "neds.yml"
  when: nso_ned_signed_binaries is defined and nso_ned_signed_binaries
  tags:
    - "nso_neds"

- name: main | Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - "always"

- name: main | NETSIM devices
  ansible.builtin.include_tasks: "netsim.yml"
  when: nso_netsim is defined and nso_netsim
  tags:
    - "nso_netsim"

- name: main | Configuration
  ansible.builtin.include_tasks: "config.yml"
  tags:
    - "nso_config"

- name: main | Cleanup
  ansible.builtin.include_tasks: "cleanup.yml"
  tags:
    - "always"
