---
- name: runtime | Create NSO runtime
  ansible.builtin.shell: "source {{ nso_install_dir }}/ncsrc && ncs-setup --dest {{ nso_runtime_dir }}"
  args:
    executable: /bin/bash
    creates: "{{ nso_runtime_dir }}"

- name: runtime | Correct permissions for NSO SSH key
  ansible.builtin.file:
    path: "{{ nso_install_dir }}/etc/ncs/ssh/ssh_host_ed25519_key"
    mode: '0755'

- name: runtime | Register NSO status
  ansible.builtin.shell: "source {{ nso_install_dir }}/ncsrc && ncs --status"
  args:
    executable: /bin/bash
  register: ncs_status
  ignore_errors: true
  no_log: true

- name: runtime | Start NSO
  ansible.builtin.shell: "cd {{ nso_runtime_dir }} && source {{ nso_install_dir }}/ncsrc && ncs --with-package-reload"
  args:
    executable: /bin/bash
  when: ncs_status.rc > 0

- name: runtime | Create NSO runtime configuration
  ansible.builtin.template:
    src: "local.ncs.conf.j2"
    dest: "{{ nso_runtime_dir }}/ncs.conf"
    mode: 0664
  notify: "Reload nso runtime config"
