---
- name: yang-files | Create directory for external YANG files
  ansible.builtin.file:
    path: "{{ nso_yang_dir }}"
    state: directory
    mode: '0755'

- name: yang-files | Download external YANG files
  ansible.builtin.get_url:
    url: "{{ item.uri }}"
    dest: "{{ nso_yang_dir }}/{{ item.name }}"
    mode: 0755
  loop: "{{ nso_yang_files }}"

- name: yang-files | Symlink external YANG files
  ansible.builtin.file:
    src: "{{ nso_yang_dir }}/{{ item.name }}"
    dest: "{{ nso_install_dir }}/src/ncs/yang/{{ item.name }}"
    state: link
  loop: "{{ nso_yang_files }}"

- name: yang-files | Create fxs files from external YANG files
  ansible.builtin.shell: "cd {{ nso_install_dir }}/etc/ncs && source {{ nso_install_dir }}/ncsrc && yanger -f fxs {{ nso_install_dir }}/src/ncs/yang/{{ item.name }}"
  args:
    executable: /bin/bash
    creates: "{{ nso_install_dir }}/etc/ncs/{{ item.name | replace('.yang', '.fxs') }}"
  loop: "{{ nso_yang_files }}"
