---
# handlers file for ansible-nso-local-install
- name: Reload nso runtime config
  ansible.builtin.shell: "cd {{ nso_runtime_dir }} && source {{ nso_install_dir }}/ncsrc && ncs --reload"
  args:
    executable: /bin/bash

- name: Reload nso packages
  ansible.builtin.shell: "cd {{ nso_runtime_dir }} && source {{ nso_install_dir }}/ncsrc && echo 'request packages reload' | ncs_cli -u admin"
  args:
    executable: /bin/bash
