---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: python310
    image: python:3.10-slim
    platform: linux/amd64
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_enabled: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false

lint: |
  set -e
  ansible-lint .

verifier:
  name: ansible
